<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-08-16T21:53:35+10:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'api_keys' => array(
        'google' => array(
            'maps' => '',
        ),
    ),
);
