<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-08-16T21:58:18+10:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'version_installed' => '1.3.1',
    'sites' => array(
        'default' => array(
            'name' => 'FossickersDoom',
        ),
    ),
    'misc' => array(
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1471348420,
        'latest_version' => '1.3.1',
    ),
);
